"""Little local web UI for the equation solver.

    .venv/bin/python app.py     ->  http://127.0.0.1:5001

Upload a photo of a handwritten equation; get back the segmentation boxes,
what each symbol was classified as (with confidence), and the answer.
"""
import base64
import io
import os
import re
import tempfile
import traceback

from flask import Flask, jsonify, render_template, request
from PIL import Image, ImageDraw

from classes import class_to_display
from pipeline import load_model, solve_image
from segment import UnreadableImageError, normalize_polarity
from solver import ParseError

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 16 * 1024 * 1024  # 16 MB

MODEL = None
CLASSES = None

HERE = os.path.dirname(os.path.abspath(__file__))

# One-click demos. Only entries whose file actually exists are offered --
# test_equations/ is generated by make_test_equations.py and may be absent.
EXAMPLE_CANDIDATES = [
    ("equation", os.path.join(HERE, "test_equations", "eq_001.png"),
     "a synthetic equation built from held-out symbols"),
    ("long equation", os.path.join(HERE, "test_equations", "eq_007.png"),
     "another synthetic equation"),
    ("light-on-dark", os.path.join(HERE, os.pardir, "test_images", "seven.jpg"),
     "MNIST-style render, inverted polarity"),
]


def available_examples():
    return [
        {"name": name, "note": note}
        for name, path, note in EXAMPLE_CANDIDATES
        if os.path.exists(path)
    ]


def example_path(name):
    for n, path, _note in EXAMPLE_CANDIDATES:
        if n == name and os.path.exists(path):
            return path
    return None


def get_model():
    global MODEL, CLASSES
    if MODEL is None:
        MODEL, CLASSES = load_model()
    return MODEL, CLASSES


def annotate(image_path, boxes, symbols, confidences):
    """Draw the detected boxes + labels onto a copy of the upload."""
    img = Image.open(image_path).convert("RGB")

    # scale line/text weight with image size so a 1600px photo and a
    # 200px render both come out legible
    scale = max(1, int(min(img.size) / 220))
    draw = ImageDraw.Draw(img)

    for (x0, y0, x1, y1), sym, conf in zip(boxes, symbols, confidences):
        # green when confident, amber when the model is hedging
        color = (34, 197, 94) if conf >= 0.8 else (245, 158, 11)
        draw.rectangle([x0, y0, x1, y1], outline=color, width=2 * scale)

        label = f"{class_to_display(sym)} {conf * 100:.0f}%"
        tx, ty = x0, max(0, y0 - 11 * scale)
        try:
            bbox = draw.textbbox((tx, ty), label)
            draw.rectangle(
                [bbox[0] - 2, bbox[1] - 2, bbox[2] + 2, bbox[3] + 2], fill=color
            )
        except Exception:
            pass
        draw.text((tx, ty), label, fill=(255, 255, 255))

    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode("ascii")


def preview_of(image_path):
    """What the segmenter actually sees, after polarity normalization."""
    import cv2

    img = cv2.imread(str(image_path), cv2.IMREAD_GRAYSCALE)
    normalized = normalize_polarity(img)
    buf = io.BytesIO()
    Image.fromarray(normalized).save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode("ascii")


def run_on(path):
    """Shared prediction body for both uploads and built-in examples."""
    model, classes = get_model()
    try:
        out = solve_image(path, model=model, classes=classes)
    except ParseError as e:
        # Rewrite to something a user can act on. The underlying messages
        # carry the temp-file path, which is noise here (and shouldn't be
        # echoed back to the browser).
        msg = str(e)
        if "no symbols found" in msg:
            friendly = ("No symbols found. Try a sharper photo, or one with more "
                        "contrast between the ink and the paper.")
        elif "could not parse" in msg:
            quoted = re.search(r"'([^']*)'", msg)
            read_as = f" Read it as “{quoted.group(1)}”." if quoted else ""
            friendly = ("Those symbols don't form a valid expression."
                        + read_as
                        + " Usually a misread symbol, or two symbols written too "
                          "close together and merged.")
        elif "division by zero" in msg:
            friendly = "That expression divides by zero."
        else:
            friendly = msg
        # still return the normalized view so the failure is diagnosable
        return {"error": friendly, "normalized": preview_of(path)}

    return {
        "expression": out["expression"],
        "result": out["result"],
        "symbols": [class_to_display(s) for s in out["symbols"]],
        "confidences": [round(c, 4) for c in out["confidences"]],
        "avg_confidence": round(out["avg_confidence"], 4),
        "annotated": annotate(path, out["boxes"], out["symbols"], out["confidences"]),
        "normalized": preview_of(path),
    }


@app.route("/")
def index():
    return render_template("index.html", examples=available_examples())


@app.route("/example/<name>", methods=["POST"])
def example(name):
    path = example_path(name)
    if path is None:
        return jsonify({"error": f"unknown example: {name}"}), 404
    try:
        return jsonify(run_on(path))
    except Exception as e:
        traceback.print_exc()
        return jsonify({"error": f"{type(e).__name__}: {e}"}), 500


@app.route("/predict", methods=["POST"])
def predict():
    upload = request.files.get("image")
    if upload is None or upload.filename == "":
        return jsonify({"error": "no file uploaded"}), 400

    suffix = os.path.splitext(upload.filename)[1].lower() or ".png"
    if suffix not in (".png", ".jpg", ".jpeg", ".bmp", ".webp"):
        return jsonify({"error": f"unsupported file type: {suffix}"}), 400

    # segment_equation reads from a path (cv2.imread), so stage the upload
    # in a temp file and remove it immediately after -- uploads are never
    # retained on disk.
    tmp = tempfile.NamedTemporaryFile(suffix=suffix, delete=False)
    try:
        upload.save(tmp.name)
        tmp.close()
        return jsonify(run_on(tmp.name))
    except UnreadableImageError:
        return jsonify({"error": "That file isn't a readable image."}), 400
    except Exception as e:
        traceback.print_exc()
        return jsonify({"error": f"{type(e).__name__}: {e}"}), 500
    finally:
        try:
            os.unlink(tmp.name)
        except OSError:
            pass


if __name__ == "__main__":
    print("loading model...")
    get_model()
    print("ready -> http://127.0.0.1:5001")
    app.run(host="127.0.0.1", port=5001, debug=False)
